### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by AnonymousX86**

### CODE REVIEW

**Comment by bentasker** [comment]
Hi, not sure why you closed out the pull?

LGTM apart from a couple of things

- Removal of license/copyright statement
- Removal of the LICENSE file

Other than those, I'd be happy enough to merge this (though as you've probably already figured, I'm not actively maintaining this anymore)

**Comment by AnonymousX86** [comment]
Hi, I've accidentally made a PR to the origin branch instead of my fork. If you'd like to merge my changes I (will be happy and...) could make another PR with all changes that I made. Check out my changes here: <https://github.com/AnonymousX86/Wake-On-Lan-Python>.

**Comment by bentasker** [comment]
Ah, that makes sense, I did similar the other day.

Changes look good in general - the only thing I'd caution a little against are these two commits:

- https://github.com/AnonymousX86/Wake-On-Lan-Python/commit/88993865807fdaaa81bcc089ccdc3901aa84b68d
- https://github.com/AnonymousX86/Wake-On-Lan-Python/commit/c4abbc13126c424f8a47dddde3ccfcc8bf91469f

In those you've removed the original author's names (mine included) and license (PSFv2), relicensed under MIT and assigned copyright to yourself. Some devs will react quite strongly to those sort of changes :)

I've not looked at whether PSF and MIT are compatible (I _think_ they are), but it's generally considered good etiquette to include earlier authors in copyright statements.

To be clear, I'm not too worried on this script, but the codebase is originally derived from a script written by Fadly Tabrani (which is where the PSF license came from).

But yeah, other than that, please raise a pull - I'll be happy to merge

**Comment by AnonymousX86** [comment]
Of course, my fork could have its own license. But when we'd like to merge then the license should match the origin one.
Updated in: 573dbd3cca780abdb3c00ed02372ce7f3f344463

**Pull request closed without merging**
